### ISSUE TITLE
[fontscan] Provide precise Location in FontMap.AddFace

### ISSUE THREAD

**Issue by benoitkugler** [go-text/typesetting#112]
I use `FontMap.AddFace` to have control about the description registered with a font, but I would also control the file identifier.
That is, I would like to also pass a `Location`. For now, the package generate a synthetic file name with 
`out.Location.File = fmt.Sprintf("%v", md)` (`md` being the font description provided by the caller).

Would you be OK to change the signature to `AddFace(face font.Face, id Location, md meta.Description)` ?

The previous behavior could be easily obtained with 
`AddFace(face font.Face, Location{File: fmt.Sprintf("%v", md)}, md meta.Description)`

Pinging @whereswaldon as code author

**Comment by whereswaldon** [comment]
I have no objection; do it!
