### ISSUE TITLE
fontscan doesn't have a way to detect whether the face is monotype or not

### ISSUE THREAD

**Issue by hajimehoshi** [go-text/typesetting#113]
https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/fontscan#FontMap.FontMetadata

FontMetadata returns a family name and an aspect, but doesn't return whether the font is monospace or not.

https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/opentype/api/metadata#Metadata

When a font is loaded via a loader, it is possible to know the monospace info.

Would it be possible to get this info via fontscan?

**Comment by hajimehoshi** [comment]
Just out of curiosity, why doesn't [`font.Face`](https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/opentype/api/font#Font) have metadata info?

**Comment by benoitkugler** [comment]
> Just out of curiosity, why doesn't [`font.Face`](https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/opentype/api/font#Font) have metadata info?

The metadata information are not required to shape/render glyphs, which is the primary job of face.Face. So it is about separation of concerns.

**Comment by benoitkugler** [comment]
> https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/fontscan#FontMap.FontMetadata
> 
> FontMetadata returns a family name and an aspect, but doesn't return whether the font is monospace or not.
> 
> https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/opentype/api/metadata#Metadata
> 
> When a font is loaded via a loader, it is possible to know the monospace info.

We initially thought about adding this information into the query, but it turns out that : 

- computing if a font is monospace is rather expensive 
- using a special attribute is generally not how other systems handle monospace fonts. They rather use an appropriate _family_ name, either with the generic `monospace` value or with a precise font name.



> Would it be possible to get this info via fontscan?

So the idea is that we could, but it is not clear if we _should_. Is using the generic `monospace` family a decent solution for you ?
Said otherwise, what would be your use case that _really_ requires this property  ?

**Comment by hajimehoshi** [comment]
> The metadata information are not required to shape/render glyphs, which is the primary job of face.Face. So it is about separation of concerns.

Wouldn't it be more natural that the metadata belongs to font faces, rather than how to load them?

> Said otherwise, what would be your use case that really requires this property ?

I don't know, maybe I don't have actual usecases, but I felt this being a little inconsistent.

**Comment by whereswaldon** [comment]
> https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/fontscan#FontMap.FontMetadata
> 
> FontMetadata returns a family name and an aspect, but doesn't return whether the font is monospace or not.
> 
> https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231120180320-af78120ccb13/opentype/api/metadata#Metadata
>
> When a font is loaded via a loader, it is possible to know the monospace info.

This is a mistake. We used to surface this info in the metadata (I naively pushed for it), but it was incredibly expensive to compute whether a font was actually monospace. You basically have to iterate all glyphs within the font checking for uniform width, and that's prohibitively expensive to do on all system fonts.

We should probably remove the field from the Metadata struct entirely. It isn't clear to the caller that requesting the metadata will trigger an expensive scan of font data.

> Wouldn't it be more natural that the metadata belongs to font faces, rather than how to load them?

I've never found separating them to be especially useful either. I usually need the description/metadata everywhere in my code that I manage fonts, so I have to plumb them alongside one another. I would have no objection to combining them somehow.

**Comment by benoitkugler** [comment]
#130 has added two methods  `(*Font) IsMonospace() bool` and `(*Font) Describe() Description`  which should help with this issue.
So I'm closing it for now, feel free to reopen if you feel there is still something actionnable to discuss.
