### ISSUE TITLE
Get the ID of the ligature glyph for a given string

### ISSUE THREAD

**Issue by akiyosi** [go-text/typesetting#131]
Is there a way to get the glyph ID of each character for a given string? 
Please note that I expect the glyph IDs here to be those to which the ligatures have been applied.

**Comment by hajimehoshi** [comment]
You can get an [`shaping.Output`](https://pkg.go.dev/github.com/go-text/typesetting/shaping#Output) by shaping like [`(&shaping.HarfbuzzShaper{}).Shape`](https://pkg.go.dev/github.com/go-text/typesetting/shaping#HarfbuzzShaper.Shape). An output includes [`shaping.Glyph`](https://pkg.go.dev/github.com/go-text/typesetting/shaping#Glyph), and this includes a glyph ID.

**Comment by akiyosi** [comment]
@hajimehoshi 
Thanks for the advice!
I was able to get a list of glyph IDs to which the ligature was applied using the approach you gave me.
This Issue is closed.
