### ISSUE TITLE
Would it be possible to put a link to Ebitengine at README?

### ISSUE THREAD

**Issue by hajimehoshi** [go-text/typesetting#155]
Hi,

I am Hajime, the author of [a 2D game engine for Go "Ebitengine"](https://ebitengine.org).

As of v2.7.0, [Ebitengine adopted go-text/typesettings for text rendering](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/text/v2). I was wondering if you could put a link to Ebitengine on the README, besides the other great projects Fyne and Gio.

Thanks,

**Comment by benoitkugler** [comment]
Well, I'm totally OK with it, thank you for using go-text !
