### ISSUE TITLE
High memory allocation

### ISSUE THREAD

**Issue by Bluebugs** [go-text/typesetting#53]
Harfbuzz shaper Shape() function does generate a large amount of memory allocation due to the call to harfbuzz.NewFont() at : https://github.com/go-text/typesetting/blob/main/shaping/shaper.go#L77 . I have done a quick/hacky local experiment by putting that font in a map cache and the resulting operation save significant amount of memory allocation and seems to also improve performance significantly.

Does anyone have an idea on what would be the proper approach to cache this font structure?

**Comment by whereswaldon** [comment]
@benoitkugler Can that type be reused? If so, it does seem like it would be worthwhile to add tunable LRU caching for it.
