### ISSUE TITLE
Issue in parsing some bitmap fonts

### ISSUE THREAD

**Issue by andydotxyz** [go-text/typesetting#74]
On using the note sans colour emoji font (https://fonts.google.com/noto/specimen/Noto+Color+Emoji) I get a font loaded that claims to be SVG format, but the data slice is `nil` for standard emoji character lookup.

I am not sure if it should be reporting PNG or SVG, but the data being nil meant I could not guess ;).

**Comment by whereswaldon** [comment]
@andydotxyz We use this exact font in some Gio examples and it reports PNG data. [Here's the place where we decode that.](https://git.sr.ht/~eliasnaur/gio/tree/main/item/text/gotext.go#L646) I can't explain why go-text would give you different results for the same font.

**Comment by andydotxyz** [comment]
Yeah it is a bit strange. The following code demos it:

```go
	text := "😀"
	data, _ := os.Open("/Users/andy/Downloads/Noto_Color_Emoji/NotoColorEmoji-Regular.ttf")
	f, _ := font.ParseTTF(data)
	in := shaping.Input{
		Text:     []rune(text),
		RunStart: 0,
		RunEnd:   len(text),
		Face:     f,
		Size:     fixed.I(24),
	}
	out := (&shaping.HarfbuzzShaper{}).Shape(in)

	if f.GlyphData(out.Glyphs[0].GlyphID).(api.GlyphBitmap).Format != api.PNG {
		t.Error("Wrong format reported")
	}
```

**Comment by andydotxyz** [comment]
Thanks, I was chasing the wrong thread. It was indeed an SVG font so no error with being not PNG. Once ascertained casting to GlyphSVG instead of GlyphBitmap did indeed reveal a Source field with the content as expected.

Sorry for the confusion.

**Comment by benoitkugler** [comment]
> Thanks, I was chasing the wrong thread. It was indeed an SVG font so no error with being not PNG. Once ascertained casting to GlyphSVG instead of GlyphBitmap did indeed reveal a Source field with the content as expected.
> 
> Sorry for the confusion.

No worries, thank you for double checking that. Should we close this issue ?

**Comment by andydotxyz** [comment]
Oops sorry :)
