### ISSUE TITLE
Float representation

### ISSUE THREAD

**Issue by benoitkugler** [go-text/typesetting#8]
I would like to discuss the choice of the actual representation for floats. I think there is two options : `float32` or `fixed.Int26_6`. The `x/image/font/sfnt` package uses `fixed.Int26_6` but I'm not sure I understand why. Do we really need a fixed point representation ? 

From what I've understood, the C libraries Harbuzz and Pango uses regular float (or double), and it seems that Fyne also favors `float32`.

It is not a fondamental question, but using `float32` would simplify the implementation of [go-text/shaping](go-text/shaping) and [go-text/font](go-text/font).

**Comment by whereswaldon** [comment]
I think this issue wandered quite far from the initial question, and I don't know if there are any outstanding todos from this conversation. We have a rendering package now, and we use fixed point values in the API. I'm going to close this for now.
