### ISSUE TITLE
Better system font fallback

### ISSUE THREAD

**Issue by whereswaldon** [go-text/typesetting#86]
I'm frequently hitting the following scenario:

- I've tried to display a string containing many writing systems. I may or may not have configured several families on this string.
- The default fallback generates a list of candidate families that does not cover all of the writing systems used in the string.
- Portions of the string using writing systems that for which no default family was found are displayed as tofu, despite my system having installed fonts with rune coverage

I totally understand *why* this scenario is happening, but it really isn't what users or application developers expect. If we have a font installed with the right rune coverage, we expect to use it rather than display tofu.

Is there a technical limitation that prevents us from building a nice data structure that lets us query the known font rune coverages efficiently to find *any* font with coverage of a rune? @benoitkugler? We'd only need it if we couldn't find any font with appropriate coverage in the configured families or manually added fonts.

**Comment by whereswaldon** [comment]
If we could implement this, it would solve @andydotxyz's concern around emoji that was discussed [here](https://github.com/go-text/typesetting/pull/63#issuecomment-1620473157)

**Comment by benoitkugler** [comment]
I guess we could add another loop using all the fonts (not only the so called 'candidates')

To speed up the process, we may use the script as a first filter: 
- register the script supported by a font (using its rune coverage)
- ahead of time, build a map[Script][]Font 
- in resolve face, first lookup into this map and iterate only over the associated fonts

What do you think?

**Comment by whereswaldon** [comment]
That sounds pretty reasonable as a first step. I actually experimented with iterating the entire database locally, but it seemed unlikely to be efficient enough. What's the best way to determine the list of supported scripts using rune coverage? I can take a stab at implementing this.

**Comment by benoitkugler** [comment]
> That sounds pretty reasonable as a first step. I actually experimented with iterating the entire database locally, but it seemed unlikely to be efficient enough. What's the best way to determine the list of supported scripts using rune coverage? I can take a stab at implementing this.

As a start, when building the rune coverage, we would hook a `script.LookupScript` for each rune.

It may be too expensive though.. a smatter approach would be to directly loop through the ranges which constitute a script, at the same time as the cmap, to avoid having to iterate for each rune.
