### ISSUE TITLE
Implement font language coverage and querying

### ISSUE THREAD

**Issue by whereswaldon** [go-text/typesetting#95]
This has been discussed previously (see below the hr)

I've discovered what I think is a compelling use case for including language info in footprints: determining the "primary" font of a piece of text. I'd like to set the default line height for a paragraph to the builtin line height of the primary font in the text. However, it's difficult to define "primary" font because you can't know *a priori* what font will be used. It's chosen based on aspect and the codepoints in the text.

You could consider using heuristics like the most-frequently-occurring font within the text, but you can also trivially create pathological cases that defeat such logic.

The best option I've been able to devise is this:

> the "primary" font is the font that will be selected for the given query term when shaping the user's system language (in a UI context)

This should result in a stable choice of primary font that will work well with the rest of an application's UI.

Implementing this is tricky as there isn't a good mapping between system `language.Language` and `language.Script` (and as far as I understand, there cannot be). For that reason, I think the only way to query "which font will be used for this query when displaying the system language" is to expose a FontMap `ResolveFace`-like operation that acts on languages instead of runes. This, in turn, requires our footprints to carry supported languages so that they can be efficiently queried.

@benoitkugler Does this make sense and seem like a good approach? I'm happy to work on this feature, or split the work between us if you have a concrete idea of how to implement parts of this.

---

> By the way, I think there is one change we may safely forecast : adding the set of languages supported by a font. It may be deduced from the `runeSet`, but, similarly to the `scriptSet`, is quite expensive to compute, so I guess we would rather store it on the footprint.
> 
> I should be able to post a PR soon if you think we should add it before the index format is widely used.

_Originally posted by @whereswaldon in https://github.com/go-text/typesetting/issues/87#issuecomment-1629478341_

**Comment by benoitkugler** [comment]
Interesting approach ! Let me start with the easy answer :

> I'm happy to work on this feature, or split the work between us if you have a concrete idea of how to implement parts of this.

I think I have indeed a precise idea for the "footprint part" (inspired by fontconfig) :
- collect, for every usual languages, a representative sample (as a string)
- for performance reasons, choose a mapping between this languages to a byte (there is less than 256 languages)
- then, for each font, collect the runeSet, and filter the languages by keeping only the ones whose sample is included in the runeSet.

A langSet would be represented by a bit set :
`type langSet [8]uint32`
This would require to map `language.Language` to the internal byte code, but it would save quite some space on the index.

Having say that, I'm not sure I understand what exactly would be the `ResolveForLang` algorithm. Could you elaborate on that part?

**Comment by whereswaldon** [comment]
> Interesting approach ! Let me start with the easy answer :
> 
> > I'm happy to work on this feature, or split the work between us if you have a concrete idea of how to implement parts of this.
> 
> I think I have indeed a precise idea for the "footprint part" (inspired by fontconfig) :
> 
>     * collect, for every usual languages, a representative sample (as a string)
> 
>     * for performance reasons, choose a mapping between this languages to a byte (there is less than 256 languages)
> 
>     * then, for each font, collect the runeSet, and filter the languages by keeping only the ones whose sample is included in the runeSet.
> 
> 
> A langSet would be represented by a bit set : `type langSet [8]uint32` This would require to map `language.Language` to the internal byte code, but it would save quite some space on the index.

Sounds good to me! Just curious, is [this language metadata](https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags) unreliable?

> Having say that, I'm not sure I understand what exactly would be the `ResolveForLang` algorithm. Could you elaborate on that part?

My goal would be to identify the font matching the current query that would be used to display a given language. A simple implementation would perform the same steps as ResolveFace except would stop at the first face supporting the target language instead of testing for support of a particular rune.

Perhaps this is a bad idea, but I can't think of another way to identify the font that the user will expect to be primary within the text. If you know of other approaches, please share them. :D

**Comment by benoitkugler** [comment]
> My goal would be to identify the font matching the current query that would be used to display a given language. A simple implementation would perform the same steps as ResolveFace except would stop at the first face supporting the target language instead of testing for support of a particular rune.
> 
> Perhaps this is a bad idea, but I can't think of another way to identify the font that the user will expect to be primary within the text. If you know of other approaches, please share them. :D

Thanks for the details, I get it now. We basically want to compute the intersection, over the runes used in a given language, of the fonts supporting theses runes, that makes sense!

**Comment by benoitkugler** [comment]
> Just curious, is [this language metadata](https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags) unreliable?

This list would give you the languages, but we would also need a sample for each one.
Besides, this table is used internally by harfbuzz to convert a regular `language.Language` to the internal opentype tag.

**Comment by benoitkugler** [comment]
> I'm happy to work on this feature, or split the work between us if you have a concrete idea of how to implement parts of this.

I'm away from a computer for a week, so I would be happy to let you work on it.

**Comment by benoitkugler** [comment]
@whereswaldon  I'll take a stab at generating the language samples from fontconfig .orth files, if that's OK for you.

**Comment by whereswaldon** [comment]
Absolutely! I don't think I could tackle it myself for quite a while.
